import {StyleSheet} from 'react-native';
import {color} from '../../../../../../assets/colorConstant';
import {CommonStyles} from '../../../../../../assets/commonStyles';
import {font} from '../../../../../../assets/fonts/fontsConstant';
import {
  moderateScale,
  moderateScaleVertical,
  textScale,
} from '../../../../../utils/responsiveSize';
export const styles = StyleSheet.create({
  menuContainer: {
    flex: 1,
  },

  sliderContainer: {
    borderColor: color.S_GRAY_2,
    borderWidth: 1,
    marginHorizontal: moderateScale(16),
    borderRadius: moderateScaleVertical(16),
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScaleVertical(16),
  },
  modalButtonBottom: {
    marginBottom: moderateScaleVertical(40),
  },
  modalLabel: {
    fontFamily: font.RobotoMedium,
    fontSize: textScale(14),
    color: color.BLACK,
    marginTop: moderateScaleVertical(20),
    textAlign: 'center',
    marginBottom: 'auto',
  },
  modalLabel1: {
    fontFamily: font.RobotoMedium,
    fontSize: textScale(14),
    color: color.BLACK,

    textAlign: 'center',
  },
  buttonText: {
    color: color.WHITE,
    fontWeight: 'bold',
    fontSize: textScale(14),
    fontFamily: font.LatoBold,
    textTransform: 'uppercase',
  },
  getStarted: {
    borderColor: color.TRANSPARNT,
    borderWidth: 1,
    borderRadius: 30,
    marginTop: moderateScaleVertical(24),
    marginBottom: moderateScaleVertical(10),
    width: moderateScale(230),
    alignSelf: 'center',
  },
  scheduleCall: {
    borderColor: color.TRANSPARNT,
    borderWidth: 1,
    borderRadius: 30,
    marginTop: moderateScaleVertical(24),
    marginBottom: moderateScaleVertical(25),

    width: moderateScale(230),
    alignSelf: 'center',
  },

  heading: {
    fontSize: textScale(17),
    color: color.BLACK,
    fontWeight: '700',
    textAlign: 'left',
  },
  list: {marginHorizontal: moderateScale(4), alignItems: 'center'},
  list1: {alignItems: 'center'},
  viewAll: {
    fontSize: textScale(12),
    fontFamily: font.LatoMedium,
    color: color.BLACK,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  why: {
    ...CommonStyles.tpp_h5,
    color: color.BLACK,
    textAlign: 'left',
    fontSize: textScale(12),
    lineHeight: moderateScaleVertical(20),
    textAlignVertical: 'center',
  },
  testimonials: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: moderateScale(16),
    marginVertical: moderateScaleVertical(24),
    alignItems: 'center',
  },
  tellwhy: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: moderateScale(16),
    marginTop: moderateScaleVertical(24),
    marginBottom: moderateScaleVertical(16),
    alignItems: 'center',
  },

  benefits: {
    fontFamily: font.LatoBold,
    fontSize: textScale(18),
    color: color.BLACK,
    fontWeight: '700',
    textAlign: 'left',

    marginHorizontal: moderateScale(8),
    marginVertical: moderateScaleVertical(24),
  },
  heightTouchLine: {
    ...CommonStyles.tpp_s2,
    color: color.P_PINK,
    marginTop: moderateScaleVertical(8),
  },
  notVisible: {
    ...CommonStyles.tpp_s2,
    color: color.P_GRAY_BLACK_1,
    marginTop: moderateScaleVertical(8),
    marginHorizontal: moderateScale(16),
  },
  container: {
    marginHorizontal: moderateScale(4),
    width: moderateScale(109),
    height: moderateScaleVertical(102),
    marginBottom: moderateScaleVertical(8),
    borderRadius: moderateScale(12),
    alignItems: 'center',
    paddingVertical: moderateScaleVertical(12),
  },
  subContainer: {
    marginHorizontal: moderateScale(16),
  },
  sumbitButtonStyle: {
    marginVertical: moderateScaleVertical(80),
    alignSelf: 'center',
    paddingHorizontal: moderateScale(16),
    width: '100%',
  },
  container2: {
    marginHorizontal: moderateScale(4),
    width: moderateScale(343),
    height: moderateScaleVertical(102),
    marginBottom: moderateScaleVertical(8),
    borderRadius: moderateScale(8),
    alignItems: 'center',
    paddingVertical: moderateScaleVertical(12),
  },
  container1: {
    marginHorizontal: moderateScale(6),
    paddingHorizontal: moderateScale(8),
    width: moderateScale(154),
    height: moderateScaleVertical(190),
    paddingTop: moderateScaleVertical(12),
    borderRadius: moderateScale(16),
    alignItems: 'flex-start',
    borderWidth: 1,
    borderColor: color.S_GRAY_2,
  },
  shimmerView: {
    marginHorizontal: moderateScale(4),
  },
  testimonialView: {
    marginHorizontal: moderateScale(10),
    marginBottom: moderateScaleVertical(12),
  },
  pinkView: {
    backgroundColor: color.S_PINK,
    paddingHorizontal: moderateScale(8),
    paddingBottom: moderateScaleVertical(24),
  },
  circleContainer: {
    width: moderateScaleVertical(48),
    height: moderateScaleVertical(48),
    borderColor: color.S_GRAY_2,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: moderateScaleVertical(60),
    marginEnd: moderateScaleVertical(12),
  },
  viewMore: {
    fontFamily: font.RobotoRegular,
    fontSize: textScale(9),
    color: color.P_PINK,
    marginVertical: moderateScaleVertical(8),
    alignSelf: 'flex-end',
  },
  inactiveTitle1: {
    fontFamily: font.RobotoRegular,
    fontSize: textScale(10),
    color: color.INPUT_TEXT,
    lineHeight: moderateScaleVertical(14),
    textAlign: 'left',
  },
  inactiveTitle: {
    fontFamily: font.RobotoMedium,
    fontSize: textScale(9),
    lineHeight: moderateScaleVertical(14),
    marginHorizontal: moderateScale(8),
    color: color.INPUT_TEXT,
    marginTop: moderateScaleVertical(12),
    textAlign: 'center',
  },
  inactiveTitle3: {
    fontFamily: font.RobotoMedium,
    fontSize: textScale(9),
    lineHeight: moderateScaleVertical(14),
    marginHorizontal: moderateScale(4),
    color: color.INPUT_TEXT,
    marginTop: moderateScaleVertical(12),
    textAlign: 'center',
  },
  inactiveTitle2: {
    fontFamily: font.RobotoRegular,
    fontSize: textScale(9),
    lineHeight: moderateScaleVertical(14),
    marginHorizontal: moderateScale(8),
    color: color.INPUT_TEXT,
    marginTop: moderateScaleVertical(12),
    textAlign: 'center',
    maxWidth: moderateScale(159),
  },
  icon: {
    maxWidth: moderateScale(24),
    maxHeight: moderateScaleVertical(24),
  },

  name: {
    fontFamily: font.RobotoMedium,
    fontSize: textScale(11),
    marginTop: moderateScaleVertical(8),
    color: color.INPUT_TEXT,
    textAlign: 'left',
    lineHeight: moderateScaleVertical(16),
  },
  designation: {
    fontFamily: font.RobotoRegular,
    fontSize: textScale(10),
    marginTop: moderateScaleVertical(2),
    marginBottom: moderateScaleVertical(8),
    color: color.P_PINK,
    textAlign: 'left',
  },
  staticCardLable: {
    ...CommonStyles.tpp_p2,
    color: color.INPUT_TEXT,
  },
  sliderLabel: {
    ...CommonStyles.tpp_s1,
    fontSize: textScale(9),
    color: color.S_GRAY_4,
    fontWeight: '500',
    textAlign: 'center',
  },
  selectedCardLable: {
    ...CommonStyles.tpp_p2,
    color: color.P_PINK,
    fontWeight: '700',
  },
  button: {
    height: 30,
    width: 30,
  },
  amount: {
    ...CommonStyles.tpp_h3,
    fontSize: textScale(17),
    textAlign: 'center',
    color: color.P_PINK,
    lineHeight: moderateScaleVertical(24),
    fontWeight: '500',
    marginBottom: moderateScaleVertical(4),
  },
  earning: {
    ...CommonStyles.tpp_s2,
    fontSize: textScale(11),
    lineHeight: moderateScaleVertical(16),
    textAlign: 'center',
    color: color.INPUT_TEXT,
    fontWeight: '500',
  },
  label: {
    ...CommonStyles.tpp_h5,
    fontSize: textScale(13),
    color: color.INPUT_TEXT,
    fontWeight: '500',
  },
  sliderDummy: {
    width: '100%',
    height: 80,
    backgroundColor: color.P_PINK,
    position: 'absolute',
  },
  calloutText: {
    fontSize: textScale(10),
    color: color.P_PINK,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: moderateScaleVertical(2.1),
  },
  sliderReal: {
    backgroundColor: color.P_PINK,
    height: 80,
    borderBottomRightRadius: 100,
    borderTopRightRadius: 100,
  },
});
