import {StyleSheet} from 'react-native';
import {color} from '../../../assets/colorConstant';
import {CommonStyles} from '../../../assets/commonStyles';
import {font} from '../../../assets/fonts/fontsConstant';
import {
  moderateScale,
  moderateScaleVertical,
  textScale,
} from '../../utils/responsiveSize';
export const styles = StyleSheet.create({
  closedContainer: {
    borderWidth: 1,
    paddingRight: moderateScale(10),
    borderRadius: moderateScale(20),
    marginBottom: moderateScaleVertical(16),
    marginHorizontal: moderateScale(16),
    borderColor: color.S_GRAY_2,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    backgroundColor: color.TRANSPARNT,
  },
  toDoMemberShip: {
    flexDirection: 'row',
    marginRight: moderateScale(16),
    backgroundColor: color.WHITE,
    borderRadius: moderateScale(20),
    opacity: 0.2,
  },
  column: {
    flexDirection: 'column',
    marginHorizontal: moderateScale(12),
    paddingBottom: moderateScaleVertical(12),
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: moderateScale(16),
  },
  toDoHeading: {
    ...CommonStyles.tpp_h5,
    fontSize: textScale(13),
    marginVertical: moderateScaleVertical(8),
    lineHeight: moderateScaleVertical(20),
    minWidth: '96%',
    maxWidth: '96%',
  },
  containerConfirm: {
    flex: 0.48,
    height: moderateScaleVertical(44),
    paddingBottom: 0,
    alignSelf: 'center',
    width: moderateScale(230),
  },
  toDoText: {
    ...CommonStyles.tpp_p3,
    fontSize: textScale(10.7),
    lineHeight: moderateScaleVertical(18),
    minWidth: '96%',
    maxWidth: '96%',
  },
  lockedViewRoot: {
    zIndex: 1,
    position: 'absolute',
    flexDirection: 'column',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: moderateScale(5),
    paddingHorizontal: moderateScale(30),
    marginTop: moderateScaleVertical(16),
  },
  uploadImageView: {
    marginVertical: moderateScaleVertical(8),
  },
  uploadedImageView: {
    marginTop: moderateScaleVertical(8),
    flexDirection: 'row',
  },
  upgrade: {
    ...CommonStyles.tpp_h5,
    textAlign: 'center',
    color: color.INPUT_TEXT,
    marginLeft: moderateScale(8),
    marginBottom: moderateScaleVertical(24),
  },
  openContainer: {
    marginBottom: moderateScaleVertical(16),
    borderWidth: 1,
    borderRadius: moderateScale(20),
    marginHorizontal: moderateScale(16),
    borderColor: color.S_GRAY_2,
    paddingRight: moderateScale(10),
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  duration: {
    fontSize: textScale(6),
    color: color.WHITE,
    fontFamily: font.RobotoRegular,
    alignSelf: 'center',
    marginHorizontal: moderateScale(10),
  },
  durationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: moderateScale(15),
  },
  durationRow1: {
    ...CommonStyles.tpp_s2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: moderateScale(5),
  },
  duration1: {
    color: color.WHITE,
    fontSize: textScale(10),
    fontFamily: font.RobotoRegular,
  },
  arrowIcon: {
    marginTop: moderateScaleVertical(17),
  },
  viewMore: {
    textAlign: 'right',
    fontFamily: font.LatoBold,
    lineHeight: moderateScaleVertical(16),
    fontSize: textScale(10.7),
    color: color.P_PINK,
    marginRight: moderateScale(16),
    marginTop: moderateScaleVertical(5),
  },
  iconRow: {
    flexDirection: 'row',
    marginRight: moderateScale(46),
    justifyContent: 'space-between',
  },
  bulletView: {
    backgroundColor: color.GREY_BACKGROUND,
    height: '100%',
    borderTopLeftRadius: moderateScale(19),
    borderBottomLeftRadius: moderateScale(19),
    width: moderateScale(32),
    justifyContent: 'center',
  },
  dateText: {
    ...CommonStyles.robotoMedium14,
    marginHorizontal: moderateScale(12),
    paddingVertical: moderateScaleVertical(3),
    fontSize: textScale(10),
  },
  infoText: {
    ...CommonStyles.tpp_s1,
    marginHorizontal: moderateScale(4),

    marginTop: moderateScaleVertical(1),
    lineHeight: moderateScaleVertical(12),
    color: color.P_GRAY_BLACK_1,
  },
  linkTitle: {
    fontFamily: font.RobotoMedium,
    fontSize: textScale(11),
    lineHeight: moderateScaleVertical(16),
    color: color.P_PINK,
    maxWidth: '95%',
    marginBottom: moderateScaleVertical(4),
  },
  infoText1: {
    fontFamily: font.RobotoRegular,
    lineHeight: moderateScaleVertical(12),
    fontSize: textScale(9.6),
    color: color.S_GRAY_3,
    marginHorizontal: moderateScale(4),
    maxWidth: '95%',
  },
  borderButtonText: {
    color: color.P_PINK,
    fontSize: textScale(14),
    fontWeight: 'bold',
    fontFamily: font.LatoBold,
    textTransform: 'uppercase',
  },
  bulletUnselected: {
    width: moderateScale(16),
    height: moderateScaleVertical(16),
    marginHorizontal: moderateScale(8),
    borderWidth: 1,
    borderColor: color.S_GRAY_4,
    borderRadius: 100,
    alignSelf: 'center',
  },
  bulletSelected: {
    width: moderateScale(16),
    height: moderateScaleVertical(16),
    marginHorizontal: moderateScale(8),
    backgroundColor: color.WHITE,
    borderRadius: 100,
    alignSelf: 'center',
  },
  dateTag: {
    borderWidth: 1,
    marginTop: moderateScaleVertical(12),
    borderRadius: 14,
  },
  toDoInfoView: {
    flexDirection: 'row',
    marginBottom: moderateScaleVertical(10),
  },
  pinkViewStyles:{
    flexDirection: 'column',
    justifyContent: 'center',
    position: 'absolute',
    alignSelf: 'center',
    alignContent: 'center',
  }
});
